spring:
  application:
    name: learn-graphql

  threads:
    virtual:
      enabled: true

  graphql:
    graphiql:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true